=== bozhink/Employee-Record-System/EmployeeRecordSystem/DataFiles/employee-records.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:e="urn:schema-employee-data-records.com" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:schema-employee-data-records.com" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="data-records" type="e:dataRecordsType" />
  <xs:simpleType name="idType">
    <xs:restriction base="xs:string">
      <xs:pattern value="E\d{4,}" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="gradeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="A" />
      <xs:enumeration value="B" />
      <xs:enumeration value="C" />
      <xs:enumeration value="D" />
      <xs:enumeration value="E" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="detailsType">
    <xs:attribute name="date-of-join" type="xs:date" use="required" />
    <xs:attribute name="grade" type="e:gradeType" use="required" />
    <xs:attribute name="salary" type="xs:unsignedShort" use="required" />
  </xs:complexType>
  <xs:complexType name="codeType">
    <xs:sequence>
      <xs:element name="details" type="e:detailsType" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="id" type="e:idType" use="required" />
    <xs:attribute name="employee-name" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="dataRecordsType">
    <xs:sequence>
      <xs:element name="code" type="e:codeType" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== bozhink/Employee-Record-System/Services.Tests/EmployeeRecordSystem.Services.Tests/DataFiles/employee-records.xml
<?xml version="1.0" encoding="utf-8" ?>
<e:data-records xmlns:e="urn:schema-employee-data-records.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:employee.com employee-records.xsd">
  <e:code id="E0001" employee-name="Michael Perry">
    <e:details date-of-join="1999-02-02" grade="A" salary="1750" />
  </e:code>
  <e:code id="E0002" employee-name="Jeniffer Carell">
    <e:details date-of-join="1999-03-22" grade="A" salary="2500" />
  </e:code>
  <e:code id="E0003" employee-name="George Rice">
    <e:details date-of-join="1999-04-18" grade="A" salary="1800" />
  </e:code>
  <e:code id="E0044" employee-name="Pamela Griffin">
    <e:details date-of-join="1999-05-03" grade="A" salary="7000" />
  </e:code>
  <e:code id="E0005" employee-name="Simon Watson">
    <e:details date-of-join="1999-05-03" grade="A" salary="1650" />
  </e:code>
  <e:code id="E0006" employee-name="Daniel Allison">
    <e:details date-of-join="1999-05-13" grade="D" salary="5700" />
  </e:code>
  <e:code id="E0007" employee-name="Laura Hanse">
    <e:details date-of-join="1999-06-02" grade="C" salary="4150" />
  </e:code>
  <e:code id="E0008" employee-name="Sarah Judd">
    <e:details date-of-join="1999-09-11" grade="B" salary="2600" />
  </e:code>
  <e:code id="E0009" employee-name="Joshua Johnson">
    <e:details date-of-join="1999-09-23" grade="E" salary="7725" />
  </e:code>
  <e:code id="E0010" employee-name="Larry Gates">
    <e:details date-of-join="1999-10-20" grade="C" salary="4350" />
  </e:code>
  <e:code id="E0011" employee-name="Nicholas Harvey">
    <e:details date-of-join="1999-10-20" grade="B" salary="2720" />
  </e:code>
  <e:code id="E0012" employee-name="Michael Brown">
    <e:details date-of-join="1999-11-11" grade="A" salary="1665" />
  </e:code>
  <e:code id="E0013" employee-name="George Lewis">
    <e:details date-of-join="1999-12-07" grade="B" salary="3150" />
  </e:code>
  <e:code id="E0014" employee-name="Elaine Thorn">
    <e:details date-of-join="1999-12-13" grade="C" salary="4070" />
  </e:code>
</e:data-records>
